- name: Copy the compose file
  become: true
  template:
    src: templates/compose.yaml
    dest: "{{ docker_compose_dir }}/compose.homeassistant.yaml"
  notify: start homeassistant

- name: Flush handlers #force preceeding handler to run immediately
  meta: flush_handlers

- name: Check whether HACS component exists
  stat:
    path: '{{ docker_dir }}/homeassistant/config/custom_components/hacs'
  register: hacs_dir

- name: Install HACS in the container
  become: true
  community.docker.docker_container_exec:
    container: homeassistant
    command: /bin/bash -c "wget -O - https://get.hacs.xyz | bash -"
  when: not hacs_dir.stat.exists
  notify: restart homeassistant
  
- name: Flush handlers #force preceeding handler to run immediately
  meta: flush_handlers


