- name: Copy the compose file
  become: true
  template:
    src: templates/compose.yaml
    dest: "{{ docker_compose_dir }}/compose.homeassistant.yaml"
  register: compose_file

- name: Docker-compose up
  become: true
  notify: start homeassistant
  when: compose_file.changed

- name: Flush handlers #force preceeding handler to run immediately
  meta: flush_handlers

- name: Check whether HACS component exists
  stat:
    path: '{{ docker_dir }}/homeassistant/config/custom_components/hacs'
  register: hacs_dir

- name: Install HACS in the container
  become: true
  community.docker.docker_container_exec:
    container: homeassistant
    command: /bin/bash -c "wget -O - https://get.hacs.xyz | bash -"
  register: hacs_install
  when: not hacs_dir.stat.exists

- name: Restart homeassistant
  become: true
  notify: start homeassistant
  when: hac_install is defined

- name: Flush handlers #force preceeding handler to run immediately
  meta: flush_handlers


